#!/usr/bin/env python
import os
import csv
import sys
import psycopg2
import click


@click.command()
@click.option('-h', '--host', default='', envvar='PGHOST',
              help='Host address of the postgres database.')
@click.option('-p', '--port', default=5432, envvar='PGPORT',
              help='Port number at which the postgres instance is listening.')
@click.option('-U', '--username', 'username_opt', envvar='PGUSER',
              help='Username to connect to the postgres database.')
@click.option('-d', '--dbname', default='', envvar='PGDATABASE',
              help='database name to connect to.')
@click.argument('database', default=lambda: None, envvar='PGDATABASE', nargs=1)
@click.argument('username', default=lambda: None, envvar='PGUSER', nargs=1)
def main(database, username_opt, host, port, dbname, username):
    password = os.environ.get('PGPASSWORD', '')

    conn = psycopg2.connect(host=host, port=port, user=username_opt, password=password, database=dbname)
    with conn.cursor() as c:

        sql = sys.stdin.read()

        c.execute(sql)

        writer = csv.writer(sys.stdout)
        while True:
            row = c.fetchone()
            if row is None:
                break
            writer.writerow(row)


if __name__ == '__main__':
    main()
